### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 970

### ISSUE THREAD

**Issue by aminechraibi** [johndoe31415/pdfminify#8] opened 2021-05-06 07:07 UTC
Error while runing:
`pdfminify in.pdf out.pdf`

Stack trace:
```
Traceback (most recent call last):
  File "C:\Users\ami\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\ami\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\venvs\venv37-ml\Scripts\pdfminify.exe\__main__.py", line 4, in <module>
  File "f:\venvs\venv37-ml\lib\site-packages\pdfminify\__main__.py", line 148, in <module>
    pdf_filter.run()
  File "f:\venvs\venv37-ml\lib\site-packages\llpdf\filters\DownscaleImageOptimization.py", line 72, in run
    for (page_obj, page_content) in self._pdf.parsed_pages:
  File "f:\venvs\venv37-ml\lib\site-packages\llpdf\PDFDocument.py", line 140, in parsed_pages
    pagedata = pagedata.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 970: invalid continuation byte
```

**Comment by johndoe31415** [comment] 2021-05-06 07:19
Hey, this is very likely a malformed input PDF document that has invalid pagedata. It's impossible for me to verify without the "in.pdf" you supplied to the tool. Any chance you can create a document that exhibits the same issue which you could share?

**Comment by johndoe31415** [comment] 2021-06-16 20:34
Cannot reproduce the issue without your support. Closing the issue, please feel free to reopen when you can send me a file to reproduce the issue with.

**Closed as completed by johndoe31415** 2021-06-16 20:34 UTC
Labels: need feedback
