### ISSUE TITLE
TypeError: 'PDFXRef' object is not subscriptable

### ISSUE THREAD

**Issue by jmrichardson** [johndoe31415/pdfminify#1] opened 2018-05-09 18:25 UTC
Hi, 

I am getting this error:  

```
Traceback (most recent call last):
  File "./pdfminify/pdfminify", line 150, in <module>
    pdf_filter.run()
  File "/var/log/wm/pdfs/pdfminify/llpdf/filters/DownscaleImageOptimization.py", line 75, in run
    interpreter.run(page_content)
  File "/var/log/wm/pdfs/pdfminify/llpdf/interpreter/GraphicsInterpreter.py", line 131, in run
    self._run_command(command)
  File "/var/log/wm/pdfs/pdfminify/llpdf/interpreter/GraphicsInterpreter.py", line 119, in _run_command
    image_xref = xobjects[image_handle]
TypeError: 'PDFXRef' object is not subscriptable

```

Thanks in advance for any help

**Comment by johndoe31415** [comment] 2018-05-10 03:19
Heya, looks like you found a bug in pdfminify. Do you think you could create a minimal PDF file that shows this problem and upload it to the ticket? Otherwise it's very difficult for me to actually see what's going wrong. Also please be a bit patient, I'm currently on business travel and am not sure how fast I can get to this (although I definitely want to fix it once I can reproduce the issue).

Please be sure to also include how you ran pdfminify (i.e., the command line) and what version you used (I'm guessing current latest master)?

All the best, Joe

**Comment by johndoe31415** [comment] 2020-03-31 21:49
No reporter feedback, closing this issue. Please reopen if the issue is reproducible.

**Closed as completed by johndoe31415** 2020-03-31 21:49 UTC
Labels: need feedback
